### ISSUE TITLE
Cannot import, after installing

### ISSUE THREAD

**Issue by beef331** [kyoheiu/nmark#1]
Due to the following it's not possible to `import nmark` since nimble does not need to with the bin, and no skip directories. If you intend on shipping a binary with it [follow](https://github.com/nim-lang/nimble#hybrids). Otherwise just comment out the following.
https://github.com/kyoheiu/nmark/blob/36b76ac5a752efba2ba4c0b2e2e901d6812e5af4/nmark.nimble#L8

**Comment by kyoheiu** [comment]
Thank you, commented out.
