### ISSUE TITLE
readme parser usage 

### ISSUE THREAD

**Issue by bung87** [kyoheiu/nmark#2]
hey, nice work! the project description said it's a parser, in document looks more like a converter , I think better document it parse usage as well. 

the gitignore I used may help you clean you project files.  
```
*
!**/
!*.*

# Cache
nimcache/
rnimcache/
dnimcache/
```

**Comment by kyoheiu** [comment]
Yes, exactly. This is markdown - html converter, though internally markdown is parsed. I'll replace 'parser' with 'converter.' Thanks.

fix: typo
